# Generated by Django 4.1 on 2022-08-11 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contatos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contato',
            old_name='data_cracao',
            new_name='data_criacao',
        ),
    ]
